### ISSUE TITLE
Modify Github Action to only run on repo's owned by 'smaddis' 

### ISSUE THREAD

**Issue by msrn** [smaddis/smad-deploy-azure#33]
Currently the ``Terraform Validate and Plan`` runs on forks of this repo. They don't work because of the missing repository secrets.
Improvement:

* Modify workflow to only work on this orgs repo's

Suggested method:

```
jobs:
  terraform:
      if: github.repository_owner == 'smaddis'
      name: 'Terraform Validate and plan'
```

Info:
https://github.com/prisma/prisma/issues/3539#issuecomment-690260573
